if(KIA_SOUL)
    add_definitions(-DKIA_SOUL)
elseif(KIA_SOUL_EV)
    add_definitions(-DKIA_SOUL_EV)
elseif(KIA_NIRO)
        add_definitions(-DKIA_NIRO)
else()
    add_definitions(-DKIA_SOUL_EV)
    #message(FATAL_ERROR "No platform selected")
endif()
